sudo: required

services:
        - docker

before_install:
        - docker build -t rohan/docker-react-2  -f dockerfile.dev .

script: 
        - docker run rohan/docker-react-2 npm run test -- --coverage

deploy:
        provider: s3
        region: ap-south-1
        app: docker-react-2
        env: "DockerReact2-env"
        buckek: "elasticbeanstalk-ap-south-1-506195770656"
        docker_path: "docker-react-2"

        on:
                branch: master

        access_key_id: "$AWS_ACCESS_KEY"
        secret_access_key: " $AWS_SECRET_KEY"
        acl: public_read    


