sudo: required

services:
        - docker

before_install:
        - docker build -t rohan/docker-react-2  -f dockerfile.dev .

script: 
        - docker run rohan/docker-react-2 npm run test -- --coverage
